server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springHw
    username: postgres
    password: postgress
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
